---

- hosts: all
  become: true
  tasks:
  - name: instal the apache2 package
    apt:
      name: apache2
      update_cache: yes
      state: latest
      
  - name: start the apache service
    service:
      name: apache2
      state: started 
